// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTfp_bfwz-rQx555btpvQLoEB1ZAcVTWQ',
    appId: '1:974599206277:web:c37e67b5a50c35b79d40ec',
    messagingSenderId: '974599206277',
    projectId: 'eatright-ai-app-2025-anmol',
    authDomain: 'eatright-ai-app-2025-anmol.firebaseapp.com',
    storageBucket: 'eatright-ai-app-2025-anmol.firebasestorage.app',
    measurementId: 'G-Y3XCV32W9E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOQ3JDoyjsR_1XFbNr6F1auJttiTujVtY',
    appId: '1:974599206277:android:ad2d565546fb0a439d40ec',
    messagingSenderId: '974599206277',
    projectId: 'eatright-ai-app-2025-anmol',
    storageBucket: 'eatright-ai-app-2025-anmol.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEfowsY5q5BTOHDkrvE1u3uPtkm4X2ZIU',
    appId: '1:974599206277:ios:021d60305e17149e9d40ec',
    messagingSenderId: '974599206277',
    projectId: 'eatright-ai-app-2025-anmol',
    storageBucket: 'eatright-ai-app-2025-anmol.firebasestorage.app',
    iosBundleId: 'com.example.eatrightAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEfowsY5q5BTOHDkrvE1u3uPtkm4X2ZIU',
    appId: '1:974599206277:ios:021d60305e17149e9d40ec',
    messagingSenderId: '974599206277',
    projectId: 'eatright-ai-app-2025-anmol',
    storageBucket: 'eatright-ai-app-2025-anmol.firebasestorage.app',
    iosBundleId: 'com.example.eatrightAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTfp_bfwz-rQx555btpvQLoEB1ZAcVTWQ',
    appId: '1:974599206277:web:934c3f47bd8b64349d40ec',
    messagingSenderId: '974599206277',
    projectId: 'eatright-ai-app-2025-anmol',
    authDomain: 'eatright-ai-app-2025-anmol.firebaseapp.com',
    storageBucket: 'eatright-ai-app-2025-anmol.firebasestorage.app',
    measurementId: 'G-32Q681DW0S',
  );
}
